version: "3.8"
name: "nekosauce"
services:
  backend:
    build:
      context: ./src/backend
      args:
        BUNNY_USERNAME: ${BACKEND_BUNNY_USERNAME}
        BUNNY_PASSWORD: ${BACKEND_BUNNY_PASSWORD}
        BUNNY_REGION: ${BACKEND_BUNNY_REGION}
        BUNNY_HOSTNAME: ${BACKEND_BUNNY_HOSTNAME}
    command: "/bin/sh -c \"/app/run.sh\""
    depends_on:
      - database
      - redis
      - rabbitmq
      - flaresolverr
    volumes:
      - static:/static
    secrets:
      - BACKEND_SECRET_KEY
      - DATABASE_PASSWORD
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          memory: ${BACKEND_MEMORY_LIMIT}
        reservations:
          memory: ${BACKEND_MEMORY_RESERVATION}
  frontend:
    build:
      context: ./src/frontend
      args:
        FRONTEND_FOOTER_DISCORD_LINK: ${FRONTEND_FOOTER_DISCORD_LINK}
        FRONTEND_FOOTER_DONATE_LINK: ${FRONTEND_FOOTER_DONATE_LINK}
        FRONTEND_FOOTER_TWITTER_LINK: ${FRONTEND_FOOTER_TWITTER_LINK}
        FRONTEND_FOOTER_REDDIT_LINK: ${FRONTEND_FOOTER_REDDIT_LINK}
        FRONTEND_FUNDING_PROGRESS: ${FRONTEND_FUNDING_PROGRESS}
        FRONTEND_FUNDING_PROGRESS_FORMAT: ${FRONTEND_FUNDING_PROGRESS_FORMAT}
    command: "npm run start"
    restart: always
    env_file:
      - .env
  database:
    build: ./src/database
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database:/var/lib/postgresql/data
    secrets:
      - DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USERNAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  rabbitmq:
    image: rabbitmq:alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
  nginx:
    image: nginx:1-alpine
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - ./src/nginx/nekosauce.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/errors:/etc/nginx/errors
    secrets:
      - NGINX_CERT_CERTIFICATE
      - NGINX_CERT_PRIVATE_KEY
    ports:
      - "443:443"
    restart: always
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    restart: always
    ports:
      - "8191:8191"
secrets:
  BACKEND_SECRET_KEY:
    file: ./secrets/BACKEND_SECRET_KEY.txt
  DATABASE_PASSWORD:
    file: ./secrets/DATABASE_PASSWORD.txt
  NGINX_CERT_CERTIFICATE:
    file: ./secrets/NGINX_CERT_CERTIFICATE.pem
  NGINX_CERT_PRIVATE_KEY:
    file: ./secrets/NGINX_CERT_PRIVATE_KEY.pem
volumes:
  database:
  static: